#include <iostream>
#include <cstdlib>  // For system() function

// Function to run a command with input redirection from a file
void run_vertex_werami_with_parameters_file(const std::string &programName, const std::string &inputFileName) {
    // Construct the command with input redirection
    std::string command = "./" + programName + " < " + inputFileName;

    // Print the command being executed (for debugging purposes)
    std::cout << "Executing command: " << command << std::endl;

    // Use system() to execute the command
    int result = system(command.c_str());

    // Check if the command was executed successfully
    if (result == 0) {
        std::cout << "Program '" << programName << "' executed successfully with input from '" << inputFileName << "'." << std::endl;
    } else {
        std::cerr << "Error: Failed to execute program '" << programName << "'." << std::endl;
    }
}

/*
int main() {
    // Paths to input files generated by modify_perplex
    std::string inputFileForVertex = "vertex_input.dat";  // Replace with the actual filename
    std::string inputFileForWerami = "werami_input.dat";  // Replace with the actual filename

    // Name of executable programs
    std::string vertexProgram = "vertex";
    std::string weramiProgram = "werami";

    // Run the "vertex" program with the input file
    run_vertex_werami_with_parameters_file(vertexProgram, inputFileForVertex);

    // Run the "werami" program with the input file
    run_vertex_werami_with_parameters_file(weramiProgram, inputFileForWerami);

    return 0;
}
*/
